name: refill
description: "프랜차이즈 매장을 위한 실시간 재고 관리 및 자동 발주 앱"
publish_to: 'none'
version: 1.0.0+1                              # 앱 버전

environment:
  sdk: ^3.7.2                                 # 사용 중인 Dart SDK 버전

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8                     # iOS 스타일 아이콘
  firebase_core: ^2.32.0                      # Firebase 필수 초기화
  firebase_auth: ^4.20.0                      # Firebase 이메일/비밀번호 및 소셜 로그인
  google_sign_in: ^6.1.4                      # 구글 로그인
  firebase_database: ^10.4.5                  # Firebase Realtime Database
  cloud_functions: ^4.6.5                     # Firebase Cloud Functions 호출용
  cloud_firestore: ^4.13.0                    # Firebase Firestore 사용
  firebase_messaging: ^14.6.5                 # 푸시 알림 (FCM)
  geolocator: ^10.1.0                         # 위치 정보 가져오기
  http: ^0.13.5                               # HTTP 요청 (날씨 API 등)
  table_calendar: ^3.0.9                      # 캘린더 UI 위젯
  intl: ^0.18.1                               # 날짜, 숫자 형식화 (ex. '2025년 6월 9일')
  provider: ^6.1.1                            # 상태 관리 (State Management)
  shared_preferences: ^2.2.2                  # 로컬 저장소 (자동 발주 시간 등 저장)
  flutter_background_service: ^5.1.0          # 백그라운드 작업 실행
  flutter_background_service_android: ^6.3.0  # 안드로이드 백그라운드 서비스 지원


dev_dependencies:
  flutter_test:
    sdk: flutter                              # 테스트용 기본 패키지
  flutter_launcher_icons: ^0.13.1             # 앱 아이콘 자동 생성
  flutter_lints: ^5.0.0                       # 코드 스타일 검사기

flutter:
  uses-material-design: true                 # material 아이콘 사용

  assets:                                    # 정적 리소스 등록 (이미지 등)
    - assets/google_logo.png
    - assets/images/create_store.png
    - assets/images/invite_code.png
    - assets/images/icon.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"        # 앱 아이콘 경로